; PlatformIO Project Configuration File

[env:esp32]
platform = espressif32@^6.0.0
board = esp32dev
framework = arduino
lib_deps =
  bblanchon/ArduinoJson@^6.19.5
build_src_filter =
  +<*>
  +<../include/*.cpp>
  +<../include/*.c>
build_flags =
  -DPLATFORM_ESP32

[env:motor_test]
platform = espressif32@^6.0.0
board = esp32dev
framework = arduino
upload_port = COM3
upload_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^6.19.5
build_src_filter =
  +<main_robot.cpp>
  +<../test/motor_test_entry.cpp>
build_flags =
  -DPLATFORM_ESP32
  -DMOTOR_TEST
